### ISSUE TITLE
Permission to include on our projects page

### ISSUE THREAD

**Issue by gurpreet-** [tozny/e3db-java#25]
Hello,

Do I have permission to add your project to the Lazysodium [project's page](https://docs.lazycode.co/lazysodium/projects)? Would be good to get some links out to projects using Lazysodium. I'm currently seeing around 1000 views on the Lazysodium Java/Android/Docs pages per month.

Thanks!

**Comment by m4dc4p** [comment]
No problem - and thanks for your great work!
