### ISSUE TITLE
Issue accessing maven repo

### ISSUE THREAD

**Issue by lolsborn** [tozny/e3db-java#8]
Downloading: https://maven.tozny.com/repo/com/tozny/e3db/e3db-client-plain/2.0.1-SNAPSHOT/maven-metadata.xml

Could not transfer metadata com.tozny.e3db:e3db-client-plain:2.0.1-SNAPSHOT/maven-metadata.xml from/to tozny-repo (https://maven.tozny.com/repo): Access denied to: https://maven.tozny.com/repo/com/tozny/e3db/e3db-client-plain/2.0.1-SNAPSHOT/maven-metadata.xml , ReasonPhrase:Forbidden.
Failure to transfer com.tozny.e3db:e3db-client-plain:2.0.1-SNAPSHOT/maven-metadata.xml from https://maven.tozny.com/repo was cached in the local repository, resolution will not be reattempted until the update interval of tozny-repo has elapsed or updates are forced. Original error: Could not transfer metadata com.tozny.e3db:e3db-client-plain:2.0.1-SNAPSHOT/maven-metadata.xml from/to tozny-repo (https://maven.tozny.com/repo): Access denied to: https://maven.tozny.com/repo/com/tozny/e3db/e3db-client-plain/2.0.1-SNAPSHOT/maven-metadata.xml , ReasonPhrase:Forbidden.

**Comment by m4dc4p** [comment]
Sorry, the README is incorrect. You should pull 2.0.0.

**Comment by m4dc4p** [comment]
Updated README.

**Comment by lolsborn** [comment]
After changing to 2.0.0 I still get errors when trying to build with maven.  It looks like it's having issues with other dependencies.  I've got the following for repositories right now.

    <repositories>
        <repository>
            <id>Maven Central</id>
            <url>http://repo.maven.apache.org/maven2/</url>
        </repository>      
        <repository>
          <id>Jitpack</id>
          <url>https://jitpack.io</url>
        </repository>
        <repository>
            <id>tozny-repo</id>
            <name>Tozny Repository</name>
            <url>https://maven.tozny.com/repo</url>
        </repository>
    </repositories>

And this in the dependencies section

        <dependency>
            <groupId>commons-codec</groupId>
            <artifactId>commons-codec</artifactId>
            <version>1.10</version>
            <type>jar</type>
        </dependency>
        
        <dependency>
            <groupId>com.github.tozny</groupId>
            <artifactId>sdk-java</artifactId>
            <version>2.1.10</version>
        </dependency>
        
        <dependency>
            <groupId>com.tozny.e3db</groupId>
            <artifactId>e3db-client-plain</artifactId>
            <version>2.0.0</version>
        </dependency>
        

[ERROR] Failed to execute goal on project RestApi: Could not resolve dependencies for project com.iotas:RestApi:war:1.0-SNAPSHOT: Failed to collect dependencies at com.github.tozny:sdk-java:jar:2.1.10 -> commons-codec:commons-codec:jar:1.+: Failed to read artifact descriptor for commons-codec:commons-codec:jar:1.+: Could not transfer artifact commons-codec:commons-codec:pom:1.+ from/to tozny-repo (https://maven.tozny.com/repo): Access denied to: https://maven.tozny.com/repo/commons-codec/commons-codec/1.+/commons-codec-1.+.pom , ReasonPhrase:Forbidden. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project RestApi: Could not resolve dependencies for project com.iotas:RestApi:war:1.0-SNAPSHOT: Failed to collect dependencies at com.github.tozny:sdk-java:jar:2.1.10 -> commons-codec:commons-codec:jar:1.+

**Comment by lolsborn** [comment]
Also, of the 40 or so dependencies you guys are the only ones not available via maven central and I require a separate repository entry for each of the tozny libraries I have.

**Comment by m4dc4p** [comment]
I believe the maven error is due to the `jar` specifier in the `commons-codec` dependency. Instead, try:

```
<dependency>    
  <groupId>commons-codec</groupId>    
  <artifactId>commons-codec</artifactId>    
  <version>1.10</version>
</dependency
```

If the `jar` thing came from some guidance we gave, please let me know and I'll work on getting that fixed.

Appreciate the feedback on hosting our artifacts. The E3DB SDKs are pretty new and we are still figuring out the best way to distribute them.

**Comment by lolsborn** [comment]
I think the jar thing came from Netbeans, I removed it, but the issue seems to persist.  I even tried removing the dependency from our pom and it is still trying to pull it down from your repo.

**Comment by lolsborn** [comment]
TBH, I'm not sure what the best practice is for managing multiple repo sources in the same POM file is.  There doesn't seem to be a way to specify which source you want for individual packages.

**Comment by m4dc4p** [comment]
My experience is maven just searches all the repositories, but it's not a build system I'm using every day so I'm not positive about that.

Could you post the POM (with any sensitive info redacted) and I'd be willing to try it locally.

**Comment by lolsborn** [comment]
So it turns out the code is not being called.  The method that launches it
is commented out, so we're not currently using E3DB :-/

I'm just going to comment it out the rest of the methods for now so that I
can get going with the rest of the dependencies.

--
Steven Osborn
http://lolsborn.com

**Comment by m4dc4p** [comment]
No worries. If this comes up again let us know.
